variables:
            InjectAlmOctaneTasks: 'true'
            OctaneConnectionName: 'AZD Pipeline'
          
task:
         - task: octane-start-task@1
           inputs:
             OctaneServiceConnection: 'AZD Pipeline'
             WorkspaceList: '1001'    
          - task: octane-end-task@1
            inputs:
              OctaneServiceConnection: 'AZD Pipeline'
              WorkspaceList: '1002'
                      
