trigger:
- master

  

jobs:
          - job: AlmOctanePipelineStart
            condition: always()
            steps:
            - task: octane-connection-verifier@1
              inputs:
                OctaneServiceConnection: 'AZD Pipeline'
            - task: RunFromFileSystemTask@1
              inputs:
                testPathInput: 'AOS_UFT_Regression'
            - task: octane-start-task@1
              inputs:
                OctaneServiceConnection: 'AZD Pipeline'
                WorkspaceList: '1002'
            - task: octane-end-task@1
              inputs:
                OctaneServiceConnection: 'AZD Pipeline'
                WorkspaceList: '1002'
            
          - job: A
            dependsOn: AlmOctanePipelineStart
            steps:
            - bash: echo "A"
          
         
          
          - job: AlmOctanePipelineEnd
            condition: always()
            dependsOn:
            - AlmOctanePipelineStart
            - A
