variables:
            InjectAlmOctaneTasks: 'true'
            OctaneConnectionName: 'AZD Pipeline'
          
jobs:
          - job: AlmOctanePipelineStart
            condition: always()
            
          - job: A
            dependsOn: AlmOctanePipelineStart
            steps:
            - bash: echo "A"
          
         
          
          - job: AlmOctanePipelineEnd
            condition: always()
            dependsOn:
            - AlmOctanePipelineStart
            - A
            
