variables:
            InjectAlmOctaneTasks: 'true'
            OctaneConnectionName: 'AZD Pipeline'
jobs:
          - job: AlmOctanePipelineStart
            condition: always()
            steps:
            - task: octane-start-task@1
              inputs:
                OctaneServiceConnection: 'AZD Pipeline'
                WorkspaceList: '1002'
            - task: octane-end-task@1
              inputs:
                OctaneServiceConnection: 'AZD Pipeline'
                WorkspaceList: '1002'
            
          - job: A
            dependsOn: AlmOctanePipelineStart
            steps:
            - bash: echo "A"
          
         
          
          - job: AlmOctanePipelineEnd
            condition: always()
            dependsOn:
            - AlmOctanePipelineStart
            - A
